spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: webapi
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          medibuddy-webapi:
            client-id: ${WEB_API_CLIENT_ID:medibuddy-webapi}
            client-secret: ${WEB_API_CLIENT_SECRET:medibuddy-webapi-secret}
            scope: ${WEBAPI_CLIENT_SCOPE:webapi.full_access}
            authorization-grant-type: client_credentials
            redirect-uri: ${WEB_API_REDIRECT_URI:http://localhost:8080/login/oauth2/code/medibuddy-webapi}
            provider: medibuddy-identity
        provider:
          medibuddy-identity:
            issuer-uri: ${ISSUER_URI:http://localhost:9000}
      resourceserver:
        opaquetoken:
          client-id: ${WEB_API_CLIENT_ID:medibuddy-webapi}
          client-secret: ${WEB_API_CLIENT_SECRET:medibuddy-webapi-secret}
          introspection-uri: ${ISSUER_URI:http://localhost:9000}/oauth2/introspect

server:
  address: ${API_SERVER_ADDRESS:0.0.0.0}
  port: ${API_SERVER_PORT:8443}
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: medibuddy_pwd
    key-password: medibuddy_pwd
    key-alias: medibuddy_cert
